# Generated by Django 5.1.4 on 2024-12-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
